### ISSUE TITLE
German translation of the About page

### ISSUE THREAD

**Issue by kayschubertwebde** [smurfy/fahrplan#154]
the About page is not translated to german

**Comment by smurfy** [comment]
Hm, i think this one is not really needed.
But with one of the last versions some parts made translateable. I'll check if the rest can be too.

**Comment by leppa** [comment]
@kayschubertwebde, thanks for reporting. Some translations might be outdated because during development translation strings can be added/renamed/removed. There is a [Fahrplan translation project on Transifex](https://www.transifex.com/projects/p/fahrplan/). Feel free to join it if you didn't already. We import updated translations shortly before a new release.

@smurfy, additionally to headers and labels in `AboutPage.qml`, I think it also makes sense to translate `support` text in `about.js`. If I'm not mistaken, `qsTr()` should work in `.js` files too.

**Comment by smurfy** [comment]
@leppa I think so too, but i'm not sure if it really does, i have some far memory that it did not work in the past. But i will try. I'm atm reviewing the PR's

**Comment by smurfy** [comment]
Translated in 4075990144668f6f7c51ec5e02cf1a1e02de2bbf
