### ISSUE TITLE
Should remember train restrictions when reopening application

### ISSUE THREAD

**Issue by nikwen** [smurfy/fahrplan#187]
Currently, the train restrictions field always resets to "All trains" when reopening the application. It should remember other values.

**Comment by leppa** [comment]
I agree. In general, we should save all selected options in the search. Train restrictions were just overlooked, most probably.

I think it would also be nice to save last active tab (Journey / Timetable).

PS: I removed Ubuntu and bahn.de from title because it's valid for all platforms and services.
