### ISSUE TITLE
3.4 segfaults.

### ISSUE THREAD

**Issue by poetaster** [smurfy/fahrplan#278]
Sailfish, of course. Looks like end of the line. 

Time to fork? I'm going to pick this apart for a sailfish build.

**Comment by poetaster** [comment]
I just did a compile without any changes using the 3.4 SDK. All's well. Just works.

If you'd like I can take of maintaining?

**Comment by smurfy** [comment]
Does it work with older versions too or does it needs two builds?

I updated my other half to 3.4 now. but need to install all my sdk's again.

**Comment by poetaster** [comment]
I believe it stopped working on 3.4. Installing the sdks is indeed a pita. I've only got, currently, one device and it was flashed directly to 3.4. I can try to get my fp2 running with, 3.3 for instance. have to ask mal for an image.

My compile had only the bahn.de backend (great for me :) enabled.

**Comment by poetaster** [comment]
Ah, in the comments under: https://openrepos.net/content/smurfy/fahrplan-0
I see that some started having problems with calendar adding: Smurfy, please fix the issue with adding journeys to the calendar. It appeared when I updated the Sailfish OS to version 3.3.0 (Rokua).

But one other user notes the segfaults as of 3.4.

**Comment by poetaster** [comment]
Ah, in the comments under: https://openrepos.net/content/smurfy/fahrplan-0
At least one other user notes the segfaults as of 3.4.

Some users at: https://forum.sailfishos.org/t/fahrplan-2-0-32-2/5388/4 

mention that the old compile works for them under 3.4 and 4 ... I've asked if it was the openrepos or jolla compile

**Comment by Olf0** [comment]
Just curious: Is this still being addressed, or at least analysed?

Note that varying compilation results with different build environments (e.g., a freshly installed SFOS-SDK vs. one used for long) might be a consequence of what [Pull Request 273 "Add missing build dependencies"](https://github.com/smurfy/fahrplan/pull/273) addresses.

P.S.: @smurfy, there are [a couple of other PRs](https://github.com/smurfy/fahrplan/pulls), many of which seem to make a lot of sense and IMO are looking fine, but all are stalled since early 2019.
Some of them contain meta-questions or -statements, which may ease your life, e.g., PR #269: "@smurfy is it possible for @dayrover to get write access?"
